#!/usr/bin/env bash
# Install nginx

sudo apt-get update
sudo apt-get install -y nginx
sudo sudo ufw allow 80
echo "Hello World!" > | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
