#!/usr/bin/env bash
# install nginx and adjust the default homepage
# add redirection


apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
new_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$new_str/" /etc/nginx/sites-available/default
service nginx restart

